/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    GameMap: {
      address: "0xc3065ccc3edbadaf1c6aa1ce6a4ad0bb2bb491a2",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_mapGenerator",
              type: "address",
              internalType: "contract MapGenerator",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "advanceRound",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "calculateStorageSlots",
          inputs: [
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "estimateStorageGas",
          inputs: [
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "game",
          inputs: [],
          outputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "round",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "initialized",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "generateAndStoreMap",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getFullMap",
          inputs: [],
          outputs: [
            {
              name: "terrain",
              type: "uint8[][]",
              internalType: "enum MapGenerator.TerrainType[][]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTerrain",
          inputs: [
            {
              name: "row",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "col",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum MapGenerator.TerrainType",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTerrainBatch",
          inputs: [
            {
              name: "rows",
              type: "uint256[]",
              internalType: "uint256[]",
            },
            {
              name: "cols",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [
            {
              name: "terrains",
              type: "uint8[]",
              internalType: "enum MapGenerator.TerrainType[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isTraversable",
          inputs: [
            {
              name: "row",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "col",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mapGenerator",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MapGenerator",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "MapGenerated",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "gridSize",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "gasUsed",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RoundAdvanced",
          inputs: [
            {
              name: "round",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "CoordinatesOutOfBounds",
          inputs: [
            {
              name: "row",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "col",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "MapAlreadyInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "MapNotInitialized",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 20846,
    },
    MapGeneratorWrapper: {
      address: "0xe1aa25618fa0c7a1cfdab5d6b456af611873b629",
      abi: [
        {
          type: "function",
          name: "generateMap",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "terrain",
              type: "uint8[][]",
              internalType: "enum MapGenerator.TerrainType[][]",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "generateMapDefault",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "terrain",
              type: "uint8[][]",
              internalType: "enum MapGenerator.TerrainType[][]",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "generateMapHash",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "generateMapPacked",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "packed",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getTileAt",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "row",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "col",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum MapGenerator.TerrainType",
            },
          ],
          stateMutability: "pure",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2128,
    },
    GameFactory: {
      address: "0x36caf13412e1fd163d41641e3a8b01c4519d73bc",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "CHALLENGE_EXECUTION_WINDOW",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CHALLENGE_PERIOD",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CHALLENGE_STAKE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "GAME_COST",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ORACLE_STAKE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "PAYOUT_PER_MUSHROOM",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "PAYOUT_PER_TILE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SLASH_AMOUNT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "calculatePayout",
          inputs: [
            {
              name: "tilesDiscovered",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "mushroomsFound",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "canChallenge",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "canFinalize",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "canRevealSeed",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "canReveal",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "reason",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "challengeResult",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "claimPayout",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "computeResultHash",
          inputs: [
            {
              name: "mapHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "positionsHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "payout",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "createGame",
          inputs: [],
          outputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "depositToPool",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "executeChallenge",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "computedResultHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "computedPayout",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "finalizeChallengedGame",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "finalizeGame",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "gameResults",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "resultHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "payout",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "oracle",
              type: "address",
              internalType: "address",
            },
            {
              name: "submittedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "challenger",
              type: "address",
              internalType: "address",
            },
            {
              name: "challengedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "challengeResultHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "challengePayout",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "games",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
            {
              name: "createdAtBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum GameFactory.GameStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getBalances",
          inputs: [],
          outputs: [
            {
              name: "totalBalance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "pool",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "oracleStakesTotal",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "fees",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getGame",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
            {
              name: "createdAtBlock",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum GameFactory.GameStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getGameResult",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "resultHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "payout",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "oracle",
              type: "address",
              internalType: "address",
            },
            {
              name: "submittedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "challenger",
              type: "address",
              internalType: "address",
            },
            {
              name: "challengedAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getGamesAwaitingResolution",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getLatestGame",
          inputs: [
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getOracleCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getOracles",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPlayerGames",
          inputs: [
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isOracle",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextGameId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "oracleList",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "oraclePendingCount",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "oracleStakes",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "playerGames",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "poolBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "revealSeed",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stakeAsOracle",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "submitResult",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "resultHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "payout",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "topUpStake",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "unstakeOracle",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawFees",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawFromPool",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "ChallengeExecuted",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "computedHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "computedPayout",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "oracleCorrect",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameCreated",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "createdAtBlock",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameFinalized",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "finalPayout",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OracleSlashed",
          inputs: [
            {
              name: "oracle",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OracleStaked",
          inputs: [
            {
              name: "oracle",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OracleUnstaked",
          inputs: [
            {
              name: "oracle",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PayoutClaimed",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolDeposit",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolWithdrawal",
          inputs: [
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ResultChallenged",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "challenger",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ResultSubmitted",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "oracle",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "resultHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "payout",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SeedRevealed",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "seed",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Withdrawal",
          inputs: [
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyChallenged",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadyClaimed",
          inputs: [],
        },
        {
          type: "error",
          name: "AlreadyOracle",
          inputs: [],
        },
        {
          type: "error",
          name: "BlockHashNotAvailable",
          inputs: [],
        },
        {
          type: "error",
          name: "ChallengePeriodEnded",
          inputs: [],
        },
        {
          type: "error",
          name: "ChallengePeriodNotEnded",
          inputs: [],
        },
        {
          type: "error",
          name: "ChallengeWindowExpired",
          inputs: [],
        },
        {
          type: "error",
          name: "GameDoesNotExist",
          inputs: [],
        },
        {
          type: "error",
          name: "GameNotFinalized",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientOracleBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientOracleStake",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientPayment",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientPoolBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidGameStatus",
          inputs: [],
        },
        {
          type: "error",
          name: "NotChallenger",
          inputs: [],
        },
        {
          type: "error",
          name: "NotGameOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOracle",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "OracleHasPendingResolutions",
          inputs: [],
        },
        {
          type: "error",
          name: "ResultAlreadySubmitted",
          inputs: [],
        },
        {
          type: "error",
          name: "SeedAlreadyRevealed",
          inputs: [],
        },
        {
          type: "error",
          name: "TooEarlyToReveal",
          inputs: [],
        },
        {
          type: "error",
          name: "WithdrawalFailed",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 20846,
    },
    MapGenerator: {
      address: "0x88fe36f7463c944590e14f7310932d7397b2adf1",
      abi: [
        {
          type: "function",
          name: "generateMap",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "terrain",
              type: "uint8[][]",
              internalType: "enum MapGenerator.TerrainType[][]",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "generateMapDefault",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "terrain",
              type: "uint8[][]",
              internalType: "enum MapGenerator.TerrainType[][]",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "generateMapHash",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "generateMapPacked",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "packed",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getTileAt",
          inputs: [
            {
              name: "roll",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "row",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "col",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "gridSize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum MapGenerator.TerrainType",
            },
          ],
          stateMutability: "pure",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 20846,
    },
    ChallengeExecutor: {
      address: "0xb6adc9f7ab29c0ca71e5518d43a3db86386e4ba8",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_gameFactory",
              type: "address",
              internalType: "address",
            },
            {
              name: "_mapGenerator",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "canStartChallenge",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "canStart",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "reason",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "challenges",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "initialized",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "finalized",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "challenger",
              type: "address",
              internalType: "address",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "spawnX",
              type: "int32",
              internalType: "int32",
            },
            {
              name: "spawnY",
              type: "int32",
              internalType: "int32",
            },
            {
              name: "centerX",
              type: "int32",
              internalType: "int32",
            },
            {
              name: "currentRound",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "agentCount",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "terrainHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "tilesDiscovered",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "mushroomsFound",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "finalize",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "gameFactory",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract GameFactory",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getAgentPosition",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "agentIndex",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          outputs: [
            {
              name: "x",
              type: "int32",
              internalType: "int32",
            },
            {
              name: "y",
              type: "int32",
              internalType: "int32",
            },
            {
              name: "direction",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "vehicleType",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getChallenge",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "initialized",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "finalized",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "challenger",
              type: "address",
              internalType: "address",
            },
            {
              name: "seed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "currentRound",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "agentCount",
              type: "uint32",
              internalType: "uint32",
            },
            {
              name: "tilesDiscovered",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "mushroomsFound",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEstimatedPayout",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isSimulationComplete",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mapGenerator",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract MapGenerator",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "simulateBatch",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "numRounds",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "startChallenge",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BatchSimulated",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "fromRound",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
            {
              name: "toRound",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
            {
              name: "agentCount",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ChallengeFinalized",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "resultHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "payout",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "oracleCorrect",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ChallengeStarted",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "challenger",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "seed",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ChallengeAlreadyFinalized",
          inputs: [],
        },
        {
          type: "error",
          name: "ChallengeAlreadyInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "ChallengeNotInitialized",
          inputs: [],
        },
        {
          type: "error",
          name: "GameNotChallenged",
          inputs: [],
        },
        {
          type: "error",
          name: "SimulationNotComplete",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 20846,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
